### ISSUE TITLE
[Location Model] Lat and Lon should not be compulsory 

### ISSUE THREAD

**Issue by mishaker** [iMMAP/rh#19]

**Comment by aleemcahn** [comment]
Solved in `[d807be94767898cf483447c8c2b469e05864d33c](https://github.com/iMMAP/rh/pull/13/commits/d807be94767898cf483447c8c2b469e05864d33c)`

**Comment by aleemcahn** [comment]
Solved here `<a href="https://github.com/iMMAP/rh/pull/13/commits/d807be94767898cf483447c8c2b469e05864d33c">d807be94767898cf483447c8c2b469e05864d33c<>`

**Comment by aleemcahn** [comment]
<p dir="auto">Related: <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1366226149" data-permission-text="Title is private" data-url="https://github.com/odoo/odoo/issues/99829" data-hovercard-type="pull_request" data-hovercard-url="/odoo/odoo/pull/99829/hovercard" href="https://github.com/odoo/odoo/pull/99829">#99829</a></p>

**Comment by aleemcahn** [comment]
<p dir="auto">
Related Commit: 
<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="d807be94767898cf483447c8c2b469e05864d33c" data-permission-text="Title is private" data-url="https://github.com/iMMAP/rh/pull/13/commits/d807be94767898cf483447c8c2b469e05864d33c" data-hovercard-type="pull_request" data-hovercard-url="/iMMAP/rh/pull/d807be94767898cf483447c8c2b469e05864d33c/hovercard" href="https://github.com/iMMAP/rh/pull/13/commits/d807be94767898cf483447c8c2b469e05864d33c">d807be94767898cf483447c8c2b469e05864d33c</a></p>

**Comment by aleemcahn** [comment]
<p dir="auto">Commit: <a class="issue-link js-issue-link" href="https://github.com/iMMAP/rh/pull/13/commits/d807be94767898cf483447c8c2b469e05864d33c" data-turbo-frame="">#d807be94767898cf483447c8c2b469e05864d33c</a></p>
