### ISSUE TITLE
Simplifying currency model

### ISSUE THREAD

**Issue by mishaker** [iMMAP/rh#21]
we have too many fields in currency model. give that currency code is unique (even when the name is the same) we can only have one field (name) 

example: you have US dollar and Canadian dollar but we can save only: 

- USD 
- CAD

**Comment by aleemcahn** [comment]
Sorry Misagh!
I don't understand, what should I do? 
Remove code field and make name field unique?

**Comment by mishaker** [comment]
I am talking about here: 
https://github.com/iMMAP/rh/blob/main/rh/models.py#L88

we have three fields: 

```
code = models.CharField(max_length=15, null=True)
name = models.CharField(max_length=200, null=True)
symbol = models.CharField(max_length=15, null=True)
``` 

But we should keep only one. `name` is enough. the other two fields should be removed.

**Comment by aleemcahn** [comment]
#23
