### ISSUE TITLE
Adding activity plan for a project

### ISSUE THREAD

**Issue by mishaker** [iMMAP/rh#25]
## Summary 

Once a user created a project he should be redirected to a second page which lists all activity plans based on activities that he selected in his project. 

So as an example if I create a project with "activity 1", "activity 2" and "activity 3" I should be redirected to page similar to this one: 
<img width="774" alt="Screenshot 2022-09-27 at 11 06 47" src="https://user-images.githubusercontent.com/939309/192506655-0e7d8b31-df79-4be6-8b1c-9baef314fad8.png">

For each activity we should render its proper form. the data for each activity will be saved in ActivityPlan.

For the interface the suggestion is to use https://getbootstrap.com/docs/5.2/components/accordion/

**Comment by aleemcahn** [comment]
Solved in #27
