### ISSUE TITLE
Project creation first step

### ISSUE THREAD

**Issue by mishaker** [iMMAP/rh#33]
## Summary 

Defining fields and their meanings for project creation first step. 

### Current report hub first step:

![Image](https://user-images.githubusercontent.com/939309/206867296-2cb0b061-f603-4d2b-8788-1892a60f3cc4.png)

![Image](https://user-images.githubusercontent.com/939309/206867298-1c0283d1-3b92-4901-a662-90c9792cf3b7.png)

## Questions: 

- "Project" is called "Activity Plan" in report hub 1.0, should we change it to "project" ?
- Are all the fields necessary in this first step? 
- Clusters name are different from OCHA clusters. Which one should we use?
- Activity types are not matching OCHA activities. Is there a mapping code for them ? 
- What is the difference between "implementing partners" and "programmers partners" ? 
- Should we simply copy paste all partners and codes that we have from reporthub 1.0? 
- HRP project and non-HRP project, how are they different ? should we keep the distinction? 
- Project Code field seems to be for internal use and have no impact elsewhere. Should we keep it ?

**Comment by paballomosala** [comment]
Hi Misagh, thanks for the questions above. please see the responses from Alex and me. I can clarify any points tomorrow if needed. Responses attached in link below

[ReportHub V2 - GitHub Issues.docx](https://github.com/iMMAP/rh/files/10202726/ReportHub.V2.-.GitHub.Issues.docx)
