### ISSUE TITLE
Project creation steps

### ISSUE THREAD

**Issue by mishaker** [iMMAP/rh#34]
## Definition of how many steps (in terms of screen) there are in project creation

Example: 

1) Project title and description 
1) Adding target activities for the project
1) Adding target locations for the project 
1) Adding beneficiaries number per activity and location

Providing wireframes per each step.

**Comment by paballomosala** [comment]
I am adding the proposed projects creation workflow linked below, should provide some guidance on how the creation of the project should flow...

[RH_Project Creation Workflow.pdf](https://github.com/iMMAP/rh/files/10203122/RH_Project.Creation.Workflow.pdf)

We can discuss the wireframes in the coming stand-up meeting and I will follow up with YellowUmbrella. In the interim, if you could generate simple HTML forms that would be super useful to keep the conversation moving
