### ISSUE TITLE
RH and OCHA activity mapping

### ISSUE THREAD

**Issue by mishaker** [iMMAP/rh#37]
See if we can integrate this file with our mapping activity script.

https://immap.sharepoint.com/:x:/s/SouthandCentralAsia/EWuspLXsunNIlxivCl_Hk0gBmXPgdpBcy-eJCpNoFXPMgQ?e=wkk9DB

**Comment by paballomosala** [comment]
Draft notes/write-up on changes made to the database structure as well as some definitions
[Report Hub Activity and Indicator database.docx](https://github.com/iMMAP/rh/files/10203172/Report.Hub.Activity.and.Indicator.database.docx)

Kindly see below link to the finalised database:
[(CLEANED) ReportHub_ActivityList_2023.xlsx](https://github.com/iMMAP/rh/files/10203177/CLEANED.ReportHub_ActivityList_2023.xlsx)
